name: docker_cubeon
services:
  postgres:
    container_name: postgres_cubeon
    image: "postgres:14.5"
    env_file:
      - ./database.env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/:ro
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    container_name: pgadmin_cubeon
    image: "dpage/pgadmin4:6.15"
    env_file:
      - ./database.env
    ports:
      - "5555:80"
    depends_on:
      - postgres
    networks:
      - backend

  keycloak:
    container_name: keycloak_cubeon
    image: "jboss/keycloak:15.0.2"
    env_file:
      - ./keycloak.env
    depends_on:
      - postgres
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

volumes:
  postgres-data:


networks:
  backend:
    name: backend
    driver: bridge
